use std::path::Path;
use std::sync::Arc;

use rustc_hash::FxHashMap;
use serde::Deserialize;
use strum::EnumString;

#[derive(Debug, Clone, Copy, Deserialize, EnumString)]
#[strum(serialize_all = "camelCase")]
pub enum DataType {
    Unsigned,
    Signed,
    Float,
    Boolean,
    MacAddress,
    OctetArray,
    String,
    DateTimeSeconds,
    DateTimeMilliseconds,
    DateTimeMicroseconds,
    DateTimeNanoseconds,
    Ipv4Address,
    Ipv6Address,
    BasicList,
    SubTemplateList,
    SubTemplateMultiList,
}

fn deserialize_arc_str<'de, D>(deserializer: D) -> Result<Arc<str>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;

    Ok(Arc::from(s))
}

#[derive(Debug, Clone, Deserialize)]
pub struct IEDefinition {
    pub id: u16,
    pub enterprise_number: Option<u32>,
    #[serde(deserialize_with = "deserialize_arc_str")]
    pub name: Arc<str>,
    pub data_type: DataType,
}

#[derive(Clone)]
pub struct IERegistry {
    elements: FxHashMap<(u16, Option<u32>), IEDefinition>,
}

impl IERegistry {
    pub fn new() -> Self {
        IERegistry {
            elements: FxHashMap::default(),
        }
    }

    pub fn new_with_iana_elements() -> Self {
        let mut registry = Self::new();
        registry.add_iana_elements();
        registry
    }

    pub fn add_element(
        &mut self,
        id: u16,
        enterprise_number: Option<u32>,
        name: impl Into<Arc<str>>,
        data_type: DataType,
    ) {
        let def = IEDefinition {
            id,
            enterprise_number,
            name: name.into(),
            data_type,
        };
        self.elements.insert((id, enterprise_number), def);
    }

    pub fn lookup(&self, id: u16, enterprise_number: Option<u32>) -> Option<&IEDefinition> {
        self.elements.get(&(id, enterprise_number))
    }

    // Not common; it's okay to do it in O(n) time.
    pub fn lookup_by_name(&self, name: &str) -> Option<&IEDefinition> {
        self.elements.values().find(|def| &*def.name == name)
    }

    pub fn load_from_csv<P: AsRef<Path>>(&mut self, path: P) -> Result<usize, csv::Error> {
        let mut reader = csv::Reader::from_path(path)?;
        let mut count = 0;

        for result in reader.deserialize() {
            let def: IEDefinition = result?;
            self.elements.insert((def.id, def.enterprise_number), def);
            count += 1;
        }

        Ok(count)
    }

    fn add_iana_elements(&mut self) {
        use DataType::*;

        #[rustfmt::skip]
        let elements = [
            (1, "octetDeltaCount", Unsigned),
            (2, "packetDeltaCount", Unsigned),
            (3, "deltaFlowCount", Unsigned),
            (4, "protocolIdentifier", Unsigned),
            (5, "ipClassOfService", Unsigned),
            (6, "tcpControlBits", Unsigned),
            (7, "sourceTransportPort", Unsigned),
            (8, "sourceIPv4Address", Ipv4Address),
            (9, "sourceIPv4PrefixLength", Unsigned),
            (10, "ingressInterface", Unsigned),
            (11, "destinationTransportPort", Unsigned),
            (12, "destinationIPv4Address", Ipv4Address),
            (13, "destinationIPv4PrefixLength", Unsigned),
            (14, "egressInterface", Unsigned),
            (15, "ipNextHopIPv4Address", Ipv4Address),
            (16, "bgpSourceAsNumber", Unsigned),
            (17, "bgpDestinationAsNumber", Unsigned),
            (18, "bgpNextHopIPv4Address", Ipv4Address),
            (19, "postMCastPacketDeltaCount", Unsigned),
            (20, "postMCastOctetDeltaCount", Unsigned),
            (21, "flowEndSysUpTime", Unsigned),
            (22, "flowStartSysUpTime", Unsigned),
            (23, "postOctetDeltaCount", Unsigned),
            (24, "postPacketDeltaCount", Unsigned),
            (25, "minimumIpTotalLength", Unsigned),
            (26, "maximumIpTotalLength", Unsigned),
            (27, "sourceIPv6Address", Ipv6Address),
            (28, "destinationIPv6Address", Ipv6Address),
            (29, "sourceIPv6PrefixLength", Unsigned),
            (30, "destinationIPv6PrefixLength", Unsigned),
            (31, "flowLabelIPv6", Unsigned),
            (32, "icmpTypeCodeIPv4", Unsigned),
            (33, "igmpType", Unsigned),
            (34, "samplingInterval", Unsigned),
            (35, "samplingAlgorithm", Unsigned),
            (36, "flowActiveTimeout", Unsigned),
            (37, "flowIdleTimeout", Unsigned),
            (38, "engineType", Unsigned),
            (39, "engineId", Unsigned),
            (40, "exportedOctetTotalCount", Unsigned),
            (41, "exportedMessageTotalCount", Unsigned),
            (42, "exportedFlowRecordTotalCount", Unsigned),
            (43, "ipv4RouterSc", Ipv4Address),
            (44, "sourceIPv4Prefix", Ipv4Address),
            (45, "destinationIPv4Prefix", Ipv4Address),
            (46, "mplsTopLabelType", Unsigned),
            (47, "mplsTopLabelIPv4Address", Ipv4Address),
            (48, "samplerId", Unsigned),
            (49, "samplerMode", Unsigned),
            (50, "samplerRandomInterval", Unsigned),
            (51, "classId", Unsigned),
            (52, "minimumTTL", Unsigned),
            (53, "maximumTTL", Unsigned),
            (54, "fragmentIdentification", Unsigned),
            (55, "postIpClassOfService", Unsigned),
            (56, "sourceMacAddress", MacAddress),
            (57, "postDestinationMacAddress", MacAddress),
            (58, "vlanId", Unsigned),
            (59, "postVlanId", Unsigned),
            (60, "ipVersion", Unsigned),
            (61, "flowDirection", Unsigned),
            (62, "ipNextHopIPv6Address", Ipv6Address),
            (63, "bgpNextHopIPv6Address", Ipv6Address),
            (64, "ipv6ExtensionHeaders", Unsigned),
            (70, "mplsTopLabelStackSection", OctetArray),
            (71, "mplsLabelStackSection2", OctetArray),
            (72, "mplsLabelStackSection3", OctetArray),
            (73, "mplsLabelStackSection4", OctetArray),
            (74, "mplsLabelStackSection5", OctetArray),
            (75, "mplsLabelStackSection6", OctetArray),
            (76, "mplsLabelStackSection7", OctetArray),
            (77, "mplsLabelStackSection8", OctetArray),
            (78, "mplsLabelStackSection9", OctetArray),
            (79, "mplsLabelStackSection10", OctetArray),
            (80, "destinationMacAddress", MacAddress),
            (81, "postSourceMacAddress", MacAddress),
            (82, "interfaceName", String),
            (83, "interfaceDescription", String),
            (84, "samplerName", String),
            (85, "octetTotalCount", Unsigned),
            (86, "packetTotalCount", Unsigned),
            (87, "flagsAndSamplerId", Unsigned),
            (88, "fragmentOffset", Unsigned),
            (89, "forwardingStatus", Unsigned),
            (90, "mplsVpnRouteDistinguisher", OctetArray),
            (91, "mplsTopLabelPrefixLength", Unsigned),
            (92, "srcTrafficIndex", Unsigned),
            (93, "dstTrafficIndex", Unsigned),
            (94, "applicationDescription", String),
            (95, "applicationId", OctetArray),
            (96, "applicationName", String),
            (98, "postIpDiffServCodePoint", Unsigned),
            (99, "multicastReplicationFactor", Unsigned),
            (100, "className", String),
            (101, "classificationEngineId", Unsigned),
            (102, "layer2packetSectionOffset", Unsigned),
            (103, "layer2packetSectionSize", Unsigned),
            (104, "layer2packetSectionData", OctetArray),
            (128, "bgpNextAdjacentAsNumber", Unsigned),
            (129, "bgpPrevAdjacentAsNumber", Unsigned),
            (130, "exporterIPv4Address", Ipv4Address),
            (131, "exporterIPv6Address", Ipv6Address),
            (132, "droppedOctetDeltaCount", Unsigned),
            (133, "droppedPacketDeltaCount", Unsigned),
            (134, "droppedOctetTotalCount", Unsigned),
            (135, "droppedPacketTotalCount", Unsigned),
            (136, "flowEndReason", Unsigned),
            (137, "commonPropertiesId", Unsigned),
            (138, "observationPointId", Unsigned),
            (139, "icmpTypeCodeIPv6", Unsigned),
            (140, "mplsTopLabelIPv6Address", Ipv6Address),
            (141, "lineCardId", Unsigned),
            (142, "portId", Unsigned),
            (143, "meteringProcessId", Unsigned),
            (144, "exportingProcessId", Unsigned),
            (145, "templateId", Unsigned),
            (146, "wlanChannelId", Unsigned),
            (147, "wlanSSID", String),
            (148, "flowId", Unsigned),
            (149, "observationDomainId", Unsigned),
            (150, "flowStartSeconds", DateTimeSeconds),
            (151, "flowEndSeconds", DateTimeSeconds),
            (152, "flowStartMilliseconds", DateTimeMilliseconds),
            (153, "flowEndMilliseconds", DateTimeMilliseconds),
            (154, "flowStartMicroseconds", DateTimeMicroseconds),
            (155, "flowEndMicroseconds", DateTimeMicroseconds),
            (156, "flowStartNanoseconds", DateTimeNanoseconds),
            (157, "flowEndNanoseconds", DateTimeNanoseconds),
            (158, "flowStartDeltaMicroseconds", Unsigned),
            (159, "flowEndDeltaMicroseconds", Unsigned),
            (160, "systemInitTimeMilliseconds", DateTimeMilliseconds),
            (161, "flowDurationMilliseconds", Unsigned),
            (162, "flowDurationMicroseconds", Unsigned),
            (163, "observedFlowTotalCount", Unsigned),
            (164, "ignoredPacketTotalCount", Unsigned),
            (165, "ignoredOctetTotalCount", Unsigned),
            (166, "notSentFlowTotalCount", Unsigned),
            (167, "notSentPacketTotalCount", Unsigned),
            (168, "notSentOctetTotalCount", Unsigned),
            (169, "destinationIPv6Prefix", Ipv6Address),
            (170, "sourceIPv6Prefix", Ipv6Address),
            (171, "postOctetTotalCount", Unsigned),
            (172, "postPacketTotalCount", Unsigned),
            (173, "flowKeyIndicator", Unsigned),
            (174, "postMCastPacketTotalCount", Unsigned),
            (175, "postMCastOctetTotalCount", Unsigned),
            (176, "icmpTypeIPv4", Unsigned),
            (177, "icmpCodeIPv4", Unsigned),
            (178, "icmpTypeIPv6", Unsigned),
            (179, "icmpCodeIPv6", Unsigned),
            (180, "udpSourcePort", Unsigned),
            (181, "udpDestinationPort", Unsigned),
            (182, "tcpSourcePort", Unsigned),
            (183, "tcpDestinationPort", Unsigned),
            (184, "tcpSequenceNumber", Unsigned),
            (185, "tcpAcknowledgementNumber", Unsigned),
            (186, "tcpWindowSize", Unsigned),
            (187, "tcpUrgentPointer", Unsigned),
            (188, "tcpHeaderLength", Unsigned),
            (189, "ipHeaderLength", Unsigned),
            (190, "totalLengthIPv4", Unsigned),
            (191, "payloadLengthIPv6", Unsigned),
            (192, "ipTTL", Unsigned),
            (193, "nextHeaderIPv6", Unsigned),
            (194, "mplsPayloadLength", Unsigned),
            (195, "ipDiffServCodePoint", Unsigned),
            (196, "ipPrecedence", Unsigned),
            (197, "fragmentFlags", Unsigned),
            (198, "octetDeltaSumOfSquares", Unsigned),
            (199, "octetTotalSumOfSquares", Unsigned),
            (200, "mplsTopLabelTTL", Unsigned),
            (201, "mplsLabelStackLength", Unsigned),
            (202, "mplsLabelStackDepth", Unsigned),
            (203, "mplsTopLabelExp", Unsigned),
            (204, "ipPayloadLength", Unsigned),
            (205, "udpMessageLength", Unsigned),
            (206, "isMulticast", Unsigned),
            (207, "ipv4IHL", Unsigned),
            (208, "ipv4Options", Unsigned),
            (209, "tcpOptions", Unsigned),
            (210, "paddingOctets", OctetArray),
            (211, "collectorIPv4Address", Ipv4Address),
            (212, "collectorIPv6Address", Ipv6Address),
            (213, "exportInterface", Unsigned),
            (214, "exportProtocolVersion", Unsigned),
            (215, "exportTransportProtocol", Unsigned),
            (216, "collectorTransportPort", Unsigned),
            (217, "exporterTransportPort", Unsigned),
            (218, "tcpSynTotalCount", Unsigned),
            (219, "tcpFinTotalCount", Unsigned),
            (220, "tcpRstTotalCount", Unsigned),
            (221, "tcpPshTotalCount", Unsigned),
            (222, "tcpAckTotalCount", Unsigned),
            (223, "tcpUrgTotalCount", Unsigned),
            (224, "ipTotalLength", Unsigned),
            (225, "postNATSourceIPv4Address", Ipv4Address),
            (226, "postNATDestinationIPv4Address", Ipv4Address),
            (227, "postNAPTSourceTransportPort", Unsigned),
            (228, "postNAPTDestinationTransportPort", Unsigned),
            (229, "natOriginatingAddressRealm", Unsigned),
            (230, "natEvent", Unsigned),
            (231, "initiatorOctets", Unsigned),
            (232, "responderOctets", Unsigned),
            (233, "firewallEvent", Unsigned),
            (234, "ingressVRFID", Unsigned),
            (235, "egressVRFID", Unsigned),
            (236, "VRFname", String),
            (237, "postMplsTopLabelExp", Unsigned),
            (238, "tcpWindowScale", Unsigned),
            (239, "biflowDirection", Unsigned),
            (240, "ethernetHeaderLength", Unsigned),
            (241, "ethernetPayloadLength", Unsigned),
            (242, "ethernetTotalLength", Unsigned),
            (243, "dot1qVlanId", Unsigned),
            (244, "dot1qPriority", Unsigned),
            (245, "dot1qCustomerVlanId", Unsigned),
            (246, "dot1qCustomerPriority", Unsigned),
            (247, "metroEvcId", String),
            (248, "metroEvcType", Unsigned),
            (249, "pseudoWireId", Unsigned),
            (250, "pseudoWireType", Unsigned),
            (251, "pseudoWireControlWord", Unsigned),
            (252, "ingressPhysicalInterface", Unsigned),
            (253, "egressPhysicalInterface", Unsigned),
            (254, "postDot1qVlanId", Unsigned),
            (255, "postDot1qCustomerVlanId", Unsigned),
            (256, "ethernetType", Unsigned),
            (257, "postIpPrecedence", Unsigned),
            (258, "collectionTimeMilliseconds", DateTimeMilliseconds),
            (259, "exportSctpStreamId", Unsigned),
            (260, "maxExportSeconds", DateTimeSeconds),
            (261, "maxFlowEndSeconds", DateTimeSeconds),
            (262, "messageMD5Checksum", OctetArray),
            (263, "messageScope", Unsigned),
            (264, "minExportSeconds", DateTimeSeconds),
            (265, "minFlowStartSeconds", DateTimeSeconds),
            (266, "opaqueOctets", OctetArray),
            (267, "sessionScope", Unsigned),
            (268, "maxFlowEndMicroseconds", DateTimeMicroseconds),
            (269, "maxFlowEndMilliseconds", DateTimeMilliseconds),
            (270, "maxFlowEndNanoseconds", DateTimeNanoseconds),
            (271, "minFlowStartMicroseconds", DateTimeMicroseconds),
            (272, "minFlowStartMilliseconds", DateTimeMilliseconds),
            (273, "minFlowStartNanoseconds", DateTimeNanoseconds),
            (274, "collectorCertificate", OctetArray),
            (275, "exporterCertificate", OctetArray),
            (276, "dataRecordsReliability", Boolean),
            (277, "observationPointType", Unsigned),
            (278, "newConnectionDeltaCount", Unsigned),
            (279, "connectionSumDurationSeconds", Unsigned),
            (280, "connectionTransactionId", Unsigned),
            (281, "postNATSourceIPv6Address", Ipv6Address),
            (282, "postNATDestinationIPv6Address", Ipv6Address),
            (283, "natPoolId", Unsigned),
            (284, "natPoolName", String),
            (285, "anonymizationFlags", Unsigned),
            (286, "anonymizationTechnique", Unsigned),
            (287, "informationElementIndex", Unsigned),
            (288, "p2pTechnology", String),
            (289, "tunnelTechnology", String),
            (290, "encryptedTechnology", String),
            (291, "basicList", BasicList),
            (292, "subTemplateList", SubTemplateList),
            (293, "subTemplateMultiList", SubTemplateMultiList),
            (294, "bgpValidityState", Unsigned),
            (295, "IPSecSPI", Unsigned),
            (296, "greKey", Unsigned),
            (297, "natType", Unsigned),
            (298, "initiatorPackets", Unsigned),
            (299, "responderPackets", Unsigned),
            (300, "observationDomainName", String),
            (301, "selectionSequenceId", Unsigned),
            (302, "selectorId", Unsigned),
            (303, "informationElementId", Unsigned),
            (304, "selectorAlgorithm", Unsigned),
            (305, "samplingPacketInterval", Unsigned),
            (306, "samplingPacketSpace", Unsigned),
            (307, "samplingTimeInterval", Unsigned),
            (308, "samplingTimeSpace", Unsigned),
            (309, "samplingSize", Unsigned),
            (310, "samplingPopulation", Unsigned),
            (311, "samplingProbability", Float),
            (312, "dataLinkFrameSize", Unsigned),
            (313, "ipHeaderPacketSection", OctetArray),
            (314, "ipPayloadPacketSection", OctetArray),
            (315, "dataLinkFrameSection", OctetArray),
            (316, "mplsLabelStackSection", OctetArray),
            (317, "mplsPayloadPacketSection", OctetArray),
            (318, "selectorIdTotalPktsObserved", Unsigned),
            (319, "selectorIdTotalPktsSelected", Unsigned),
            (320, "absoluteError", Float),
            (321, "relativeError", Float),
            (322, "observationTimeSeconds", DateTimeSeconds),
            (323, "observationTimeMilliseconds", DateTimeMilliseconds),
            (324, "observationTimeMicroseconds", DateTimeMicroseconds),
            (325, "observationTimeNanoseconds", DateTimeNanoseconds),
            (326, "digestHashValue", Unsigned),
            (327, "hashIPPayloadOffset", Unsigned),
            (328, "hashIPPayloadSize", Unsigned),
            (329, "hashOutputRangeMin", Unsigned),
            (330, "hashOutputRangeMax", Unsigned),
            (331, "hashSelectedRangeMin", Unsigned),
            (332, "hashSelectedRangeMax", Unsigned),
            (333, "hashDigestOutput", Boolean),
            (334, "hashInitialiserValue", Unsigned),
            (335, "selectorName", String),
            (336, "upperCILimit", Float),
            (337, "lowerCILimit", Float),
            (338, "confidenceLevel", Float),
            (339, "informationElementDataType", Unsigned),
            (340, "informationElementDescription", String),
            (341, "informationElementName", String),
            (342, "informationElementRangeBegin", Unsigned),
            (343, "informationElementRangeEnd", Unsigned),
            (344, "informationElementSemantics", Unsigned),
            (345, "informationElementUnits", Unsigned),
            (346, "privateEnterpriseNumber", Unsigned),
            (347, "virtualStationInterfaceId", OctetArray),
            (348, "virtualStationInterfaceName", String),
            (349, "virtualStationUUID", OctetArray),
            (350, "virtualStationName", String),
            (351, "layer2SegmentId", Unsigned),
            (352, "layer2OctetDeltaCount", Unsigned),
            (353, "layer2OctetTotalCount", Unsigned),
            (354, "ingressUnicastPacketTotalCount", Unsigned),
            (355, "ingressMulticastPacketTotalCount", Unsigned),
            (356, "ingressBroadcastPacketTotalCount", Unsigned),
            (357, "egressUnicastPacketTotalCount", Unsigned),
            (358, "egressBroadcastPacketTotalCount", Unsigned),
            (359, "monitoringIntervalStartMilliSeconds", DateTimeMilliseconds),
            (360, "monitoringIntervalEndMilliSeconds", DateTimeMilliseconds),
            (361, "portRangeStart", Unsigned),
            (362, "portRangeEnd", Unsigned),
            (363, "portRangeStepSize", Unsigned),
            (364, "portRangeNumPorts", Unsigned),
            (365, "staMacAddress", MacAddress),
            (366, "staIPv4Address", Ipv4Address),
            (367, "wtpMacAddress", MacAddress),
            (368, "ingressInterfaceType", Unsigned),
            (369, "egressInterfaceType", Unsigned),
            (370, "rtpSequenceNumber", Unsigned),
            (371, "userName", String),
            (372, "applicationCategoryName", String),
            (373, "applicationSubCategoryName", String),
            (374, "applicationGroupName", String),
            (375, "originalFlowsPresent", Unsigned),
            (376, "originalFlowsInitiated", Unsigned),
            (377, "originalFlowsCompleted", Unsigned),
            (378, "distinctCountOfSourceIPAddress", Unsigned),
            (379, "distinctCountOfDestinationIPAddress", Unsigned),
            (380, "distinctCountOfSourceIPv4Address", Unsigned),
            (381, "distinctCountOfDestinationIPv4Address", Unsigned),
            (382, "distinctCountOfSourceIPv6Address", Unsigned),
            (383, "distinctCountOfDestinationIPv6Address", Unsigned),
            (384, "valueDistributionMethod", Unsigned),
            (385, "rfc3550JitterMilliseconds", Unsigned),
            (386, "rfc3550JitterMicroseconds", Unsigned),
            (387, "rfc3550JitterNanoseconds", Unsigned),
            (388, "dot1qDEI", Boolean),
            (389, "dot1qCustomerDEI", Boolean),
            (390, "flowSelectorAlgorithm", Unsigned),
            (391, "flowSelectedOctetDeltaCount", Unsigned),
            (392, "flowSelectedPacketDeltaCount", Unsigned),
            (393, "flowSelectedFlowDeltaCount", Unsigned),
            (394, "selectorIDTotalFlowsObserved", Unsigned),
            (395, "selectorIDTotalFlowsSelected", Unsigned),
            (396, "samplingFlowInterval", Unsigned),
            (397, "samplingFlowSpacing", Unsigned),
            (398, "flowSamplingTimeInterval", Unsigned),
            (399, "flowSamplingTimeSpacing", Unsigned),
            (400, "hashFlowDomain", Unsigned),
            (401, "transportOctetDeltaCount", Unsigned),
            (402, "transportPacketDeltaCount", Unsigned),
            (403, "originalExporterIPv4Address", Ipv4Address),
            (404, "originalExporterIPv6Address", Ipv6Address),
            (405, "originalObservationDomainId", Unsigned),
            (406, "intermediateProcessId", Unsigned),
            (407, "ignoredDataRecordTotalCount", Unsigned),
            (408, "dataLinkFrameType", Unsigned),
            (409, "sectionOffset", Unsigned),
            (410, "sectionExportedOctets", Unsigned),
            (411, "dot1qServiceInstanceTag", OctetArray),
            (412, "dot1qServiceInstanceId", Unsigned),
            (413, "dot1qServiceInstancePriority", Unsigned),
            (414, "dot1qCustomerSourceMacAddress", MacAddress),
            (415, "dot1qCustomerDestinationMacAddress", MacAddress),
            (417, "postLayer2OctetDeltaCount", Unsigned),
            (418, "postMCastLayer2OctetDeltaCount", Unsigned),
            (420, "postLayer2OctetTotalCount", Unsigned),
            (421, "postMCastLayer2OctetTotalCount", Unsigned),
            (422, "minimumLayer2TotalLength", Unsigned),
            (423, "maximumLayer2TotalLength", Unsigned),
            (424, "droppedLayer2OctetDeltaCount", Unsigned),
            (425, "droppedLayer2OctetTotalCount", Unsigned),
            (426, "ignoredLayer2OctetTotalCount", Unsigned),
            (427, "notSentLayer2OctetTotalCount", Unsigned),
            (428, "layer2OctetDeltaSumOfSquares", Unsigned),
            (429, "layer2OctetTotalSumOfSquares", Unsigned),
            (430, "layer2FrameDeltaCount", Unsigned),
            (431, "layer2FrameTotalCount", Unsigned),
            (432, "pseudoWireDestinationIPv4Address", Ipv4Address),
            (433, "ignoredLayer2FrameTotalCount", Unsigned),
            (434, "mibObjectValueInteger", Signed),
            (435, "mibObjectValueOctetString", OctetArray),
            (436, "mibObjectValueOID", OctetArray),
            (437, "mibObjectValueBits", OctetArray),
            (438, "mibObjectValueIPAddress", Ipv4Address),
            (439, "mibObjectValueCounter", Unsigned),
            (440, "mibObjectValueGauge", Unsigned),
            (441, "mibObjectValueTimeTicks", Unsigned),
            (442, "mibObjectValueUnsigned", Unsigned),
            (443, "mibObjectValueTable", SubTemplateList),
            (444, "mibObjectValueRow", SubTemplateList),
            (445, "mibObjectIdentifier", OctetArray),
            (446, "mibSubIdentifier", Unsigned),
            (447, "mibIndexIndicator", Unsigned),
            (448, "mibCaptureTimeSemantics", Unsigned),
            (449, "mibContextEngineID", OctetArray),
            (450, "mibContextName", String),
            (451, "mibObjectName", String),
            (452, "mibObjectDescription", String),
            (453, "mibObjectSyntax", String),
            (454, "mibModuleName", String),
            (455, "mobileIMSI", String),
            (456, "mobileMSISDN", String),
            (457, "httpStatusCode", Unsigned),
            (458, "sourceTransportPortsLimit", Unsigned),
            (459, "httpRequestMethod", String),
            (460, "httpRequestHost", String),
            (461, "httpRequestTarget", String),
            (462, "httpMessageVersion", String),
            (463, "natInstanceID", Unsigned),
            (464, "internalAddressRealm", OctetArray),
            (465, "externalAddressRealm", OctetArray),
            (466, "natQuotaExceededEvent", Unsigned),
            (467, "natThresholdEvent", Unsigned),
            (468, "httpUserAgent", String),
            (469, "httpContentType", String),
            (470, "httpReasonPhrase", String),
            (471, "maxSessionEntries", Unsigned),
            (472, "maxBIBEntries", Unsigned),
            (473, "maxEntriesPerUser", Unsigned),
            (474, "maxSubscribers", Unsigned),
            (475, "maxFragmentsPendingReassembly", Unsigned),
            (476, "addressPoolHighThreshold", Unsigned),
            (477, "addressPoolLowThreshold", Unsigned),
            (478, "addressPortMappingHighThreshold", Unsigned),
            (479, "addressPortMappingLowThreshold", Unsigned),
            (480, "addressPortMappingPerUserHighThreshold", Unsigned),
            (481, "globalAddressMappingHighThreshold", Unsigned),
            (482, "vpnIdentifier", OctetArray),
            (483, "bgpCommunity", Unsigned),
            (484, "bgpSourceCommunityList", BasicList),
            (485, "bgpDestinationCommunityList", BasicList),
            (486, "bgpExtendedCommunity", OctetArray),
            (487, "bgpSourceExtendedCommunityList", BasicList),
            (488, "bgpDestinationExtendedCommunityList", BasicList),
            (489, "bgpLargeCommunity", OctetArray),
            (490, "bgpSourceLargeCommunityList", BasicList),
            (491, "bgpDestinationLargeCommunityList", BasicList),
            (492, "srhFlagsIPv6", Unsigned),
            (493, "srhTagIPv6", Unsigned),
            (494, "srhSegmentIPv6", Ipv6Address),
            (495, "srhActiveSegmentIPv6", Ipv6Address),
            (496, "srhSegmentIPv6BasicList", BasicList),
            (497, "srhSegmentIPv6ListSection", OctetArray),
            (498, "srhSegmentsIPv6Left", Unsigned),
            (499, "srhIPv6Section", OctetArray),
            (500, "srhIPv6ActiveSegmentType", Unsigned),
            (501, "srhSegmentIPv6LocatorLength", Unsigned),
            (502, "srhSegmentIPv6EndpointBehavior", Unsigned),
            (503, "transportChecksum", Unsigned),
            (504, "icmpHeaderPacketSection", OctetArray),
            (505, "gtpuFlags", Unsigned),
            (506, "gtpuMsgType", Unsigned),
            (507, "gtpuTEid", Unsigned),
            (508, "gtpuSequenceNum", Unsigned),
            (509, "gtpuQFI", Unsigned),
            (510, "gtpuPduType", Unsigned),
            (511, "bgpSourceAsPathList", BasicList),
            (512, "bgpDestinationAsPathList", BasicList),
            (513, "ipv6ExtensionHeaderType", Unsigned),
            (514, "ipv6ExtensionHeaderCount", Unsigned),
            (515, "ipv6ExtensionHeadersFull", Unsigned),
            (516, "ipv6ExtensionHeaderTypeCountList", SubTemplateList),
            (517, "ipv6ExtensionHeadersLimit", Boolean),
            (518, "ipv6ExtensionHeadersChainLength", Unsigned),
            (519, "ipv6ExtensionHeaderChainLengthList", SubTemplateList),
            (520, "tcpOptionsFull", Unsigned),
            (521, "tcpSharedOptionExID16", Unsigned),
            (522, "tcpSharedOptionExID32", Unsigned),
            (523, "tcpSharedOptionExID16List", BasicList),
            (524, "tcpSharedOptionExID32List", BasicList),
            (525, "udpSafeOptions", Unsigned),
            (526, "udpUnsafeOptions", Unsigned),
            (527, "udpExID", Unsigned),
            (528, "udpSafeExIDList", BasicList),
            (529, "udpUnsafeExIDList", BasicList),
        ];

        elements.iter().for_each(|(id, name, data_type)| {
            self.add_element(*id, None, name.to_string(), data_type.clone());
        });
    }
}

impl Default for IERegistry {
    fn default() -> Self {
        Self::new_with_iana_elements()
    }
}
