use num_enum::{IntoPrimitive, TryFromPrimitive};

/// IANA IPFIX Information Elements (commonly used subset)
///
/// See: https://www.iana.org/assignments/ipfix/ipfix.xhtml
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, IntoPrimitive, TryFromPrimitive)]
#[repr(u16)]
pub enum InformationElement {
    OctetDeltaCount = 1,
    PacketDeltaCount = 2,
    ProtocolIdentifier = 4,
    IpClassOfService = 5,
    TcpControlBits = 6,
    SourceTransportPort = 7,
    SourceIpv4Address = 8,
    SourceIpv4PrefixLength = 9,
    IngressInterface = 10,
    DestinationTransportPort = 11,
    DestinationIpv4Address = 12,
    DestinationIpv4PrefixLength = 13,
    EgressInterface = 14,
    IpNextHopIpv4Address = 15,
    BgpSourceAsNumber = 16,
    BgpDestinationAsNumber = 17,
    BgpNextHopIpv4Address = 18,
    FlowEndSysUpTime = 21,
    FlowStartSysUpTime = 22,
    SourceIpv6Address = 27,
    DestinationIpv6Address = 28,
    SourceIpv6PrefixLength = 29,
    DestinationIpv6PrefixLength = 30,
    FlowLabelIpv6 = 31,
    IcmpTypeCodeIpv4 = 32,
    SamplingInterval = 34,
    SamplerRandomInterval = 50,
    MinimumTtl = 52,
    MaximumTtl = 53,
    FragmentIdentification = 54,
    SourceMacAddress = 56,
    PostDestinationMacAddress = 57,
    SrcVlan = 58,
    DstVlan = 59,
    IpNextHopIpv6Address = 62,
    BgpNextHopIpv6Address = 63,
    DestinationMacAddress = 80,
    PostSourceMacAddress = 81,
    ForwardingStatus = 89,
    ObservationDomainId = 149,
    FlowStartSeconds = 150,
    FlowEndSeconds = 151,
    FlowStartMilliseconds = 152,
    FlowEndMilliseconds = 153,
    FlowStartMicroseconds = 154,
    FlowEndMicroseconds = 155,
    FlowStartNanoseconds = 156,
    FlowEndNanoseconds = 157,
    FlowStartDeltaMicroseconds = 158,
    FlowEndDeltaMicroseconds = 159,
    IcmpTypeIpv4 = 176,
    IcmpCodeIpv4 = 177,
    IcmpTypeIpv6 = 178,
    IcmpCodeIpv6 = 179,
    SamplingPacketInterval = 305,
}
