use std::path::Path;

use rustc_hash::FxHashMap;
use serde::Deserialize;
use strum::EnumString;

#[derive(Debug, Clone, Deserialize, EnumString)]
#[strum(serialize_all = "camelCase")]
pub enum DataType {
    Unsigned,
    Signed,
    Float,
    Boolean,
    MacAddress,
    OctetArray,
    String,
    DateTimeSeconds,
    DateTimeMilliseconds,
    DateTimeMicroseconds,
    DateTimeNanoseconds,
    Ipv4Address,
    Ipv6Address,
    BasicList,
    SubTemplateList,
    SubTemplateMultiList,
}

#[derive(Debug, Clone, Deserialize)]
pub struct IEDefinition {
    pub id: u16,
    pub enterprise_number: Option<u32>,
    pub name: String,
    pub data_type: DataType,
}

#[derive(Clone)]
pub struct IERegistry {
    elements: FxHashMap<(u16, Option<u32>), IEDefinition>,
}

impl IERegistry {
    pub fn new() -> Self {
        IERegistry {
            elements: FxHashMap::default(),
        }
    }

    pub fn new_with_iana_elements() -> Self {
        let mut registry = Self::new();
        registry.add_iana_elements();
        registry
    }

    pub fn add_element(
        &mut self,
        id: u16,
        enterprise_number: Option<u32>,
        name: String,
        data_type: DataType,
    ) {
        let def = IEDefinition {
            id,
            enterprise_number,
            name,
            data_type,
        };
        self.elements.insert((id, enterprise_number), def);
    }

    pub fn lookup(&self, id: u16, enterprise_number: Option<u32>) -> Option<&IEDefinition> {
        self.elements.get(&(id, enterprise_number))
    }

    pub fn lookup_by_name(&self, name: &str) -> Option<&IEDefinition> {
        self.elements.values().find(|def| def.name == name)
    }

    pub fn load_from_csv<P: AsRef<Path>>(&mut self, path: P) -> Result<usize, csv::Error> {
        let mut reader = csv::Reader::from_path(path)?;
        let mut count = 0;

        for result in reader.deserialize() {
            let def: IEDefinition = result?;
            self.elements.insert((def.id, def.enterprise_number), def);
            count += 1;
        }

        Ok(count)
    }

    fn add_iana_elements(&mut self) {
        #[rustfmt::skip]
        let elements = [
            (1, "octetDeltaCount", "unsigned"),
            (2, "packetDeltaCount", "unsigned"),
            (3, "deltaFlowCount", "unsigned"),
            (4, "protocolIdentifier", "unsigned"),
            (5, "ipClassOfService", "unsigned"),
            (6, "tcpControlBits", "unsigned"),
            (7, "sourceTransportPort", "unsigned"),
            (8, "sourceIPv4Address", "ipv4Address"),
            (9, "sourceIPv4PrefixLength", "unsigned"),
            (10, "ingressInterface", "unsigned"),
            (11, "destinationTransportPort", "unsigned"),
            (12, "destinationIPv4Address", "ipv4Address"),
            (13, "destinationIPv4PrefixLength", "unsigned"),
            (14, "egressInterface", "unsigned"),
            (15, "ipNextHopIPv4Address", "ipv4Address"),
            (16, "bgpSourceAsNumber", "unsigned"),
            (17, "bgpDestinationAsNumber", "unsigned"),
            (18, "bgpNextHopIPv4Address", "ipv4Address"),
            (19, "postMCastPacketDeltaCount", "unsigned"),
            (20, "postMCastOctetDeltaCount", "unsigned"),
            (21, "flowEndSysUpTime", "unsigned"),
            (22, "flowStartSysUpTime", "unsigned"),
            (23, "postOctetDeltaCount", "unsigned"),
            (24, "postPacketDeltaCount", "unsigned"),
            (25, "minimumIpTotalLength", "unsigned"),
            (26, "maximumIpTotalLength", "unsigned"),
            (27, "sourceIPv6Address", "ipv6Address"),
            (28, "destinationIPv6Address", "ipv6Address"),
            (29, "sourceIPv6PrefixLength", "unsigned"),
            (30, "destinationIPv6PrefixLength", "unsigned"),
            (31, "flowLabelIPv6", "unsigned"),
            (32, "icmpTypeCodeIPv4", "unsigned"),
            (33, "igmpType", "unsigned"),
            (34, "samplingInterval", "unsigned"),
            (35, "samplingAlgorithm", "unsigned"),
            (36, "flowActiveTimeout", "unsigned"),
            (37, "flowIdleTimeout", "unsigned"),
            (38, "engineType", "unsigned"),
            (39, "engineId", "unsigned"),
            (40, "exportedOctetTotalCount", "unsigned"),
            (41, "exportedMessageTotalCount", "unsigned"),
            (42, "exportedFlowRecordTotalCount", "unsigned"),
            (43, "ipv4RouterSc", "ipv4Address"),
            (44, "sourceIPv4Prefix", "ipv4Address"),
            (45, "destinationIPv4Prefix", "ipv4Address"),
            (46, "mplsTopLabelType", "unsigned"),
            (47, "mplsTopLabelIPv4Address", "ipv4Address"),
            (48, "samplerId", "unsigned"),
            (49, "samplerMode", "unsigned"),
            (50, "samplerRandomInterval", "unsigned"),
            (51, "classId", "unsigned"),
            (52, "minimumTTL", "unsigned"),
            (53, "maximumTTL", "unsigned"),
            (54, "fragmentIdentification", "unsigned"),
            (55, "postIpClassOfService", "unsigned"),
            (56, "sourceMacAddress", "macAddress"),
            (57, "postDestinationMacAddress", "macAddress"),
            (58, "vlanId", "unsigned"),
            (59, "postVlanId", "unsigned"),
            (60, "ipVersion", "unsigned"),
            (61, "flowDirection", "unsigned"),
            (62, "ipNextHopIPv6Address", "ipv6Address"),
            (63, "bgpNextHopIPv6Address", "ipv6Address"),
            (64, "ipv6ExtensionHeaders", "unsigned"),
            (70, "mplsTopLabelStackSection", "octetArray"),
            (71, "mplsLabelStackSection2", "octetArray"),
            (72, "mplsLabelStackSection3", "octetArray"),
            (73, "mplsLabelStackSection4", "octetArray"),
            (74, "mplsLabelStackSection5", "octetArray"),
            (75, "mplsLabelStackSection6", "octetArray"),
            (76, "mplsLabelStackSection7", "octetArray"),
            (77, "mplsLabelStackSection8", "octetArray"),
            (78, "mplsLabelStackSection9", "octetArray"),
            (79, "mplsLabelStackSection10", "octetArray"),
            (80, "destinationMacAddress", "macAddress"),
            (81, "postSourceMacAddress", "macAddress"),
            (82, "interfaceName", "string"),
            (83, "interfaceDescription", "string"),
            (84, "samplerName", "string"),
            (85, "octetTotalCount", "unsigned"),
            (86, "packetTotalCount", "unsigned"),
            (87, "flagsAndSamplerId", "unsigned"),
            (88, "fragmentOffset", "unsigned"),
            (89, "forwardingStatus", "unsigned"),
            (90, "mplsVpnRouteDistinguisher", "octetArray"),
            (91, "mplsTopLabelPrefixLength", "unsigned"),
            (92, "srcTrafficIndex", "unsigned"),
            (93, "dstTrafficIndex", "unsigned"),
            (94, "applicationDescription", "string"),
            (95, "applicationId", "octetArray"),
            (96, "applicationName", "string"),
            (98, "postIpDiffServCodePoint", "unsigned"),
            (99, "multicastReplicationFactor", "unsigned"),
            (100, "className", "string"),
            (101, "classificationEngineId", "unsigned"),
            (102, "layer2packetSectionOffset", "unsigned"),
            (103, "layer2packetSectionSize", "unsigned"),
            (104, "layer2packetSectionData", "octetArray"),
            (128, "bgpNextAdjacentAsNumber", "unsigned"),
            (129, "bgpPrevAdjacentAsNumber", "unsigned"),
            (130, "exporterIPv4Address", "ipv4Address"),
            (131, "exporterIPv6Address", "ipv6Address"),
            (132, "droppedOctetDeltaCount", "unsigned"),
            (133, "droppedPacketDeltaCount", "unsigned"),
            (134, "droppedOctetTotalCount", "unsigned"),
            (135, "droppedPacketTotalCount", "unsigned"),
            (136, "flowEndReason", "unsigned"),
            (137, "commonPropertiesId", "unsigned"),
            (138, "observationPointId", "unsigned"),
            (139, "icmpTypeCodeIPv6", "unsigned"),
            (140, "mplsTopLabelIPv6Address", "ipv6Address"),
            (141, "lineCardId", "unsigned"),
            (142, "portId", "unsigned"),
            (143, "meteringProcessId", "unsigned"),
            (144, "exportingProcessId", "unsigned"),
            (145, "templateId", "unsigned"),
            (146, "wlanChannelId", "unsigned"),
            (147, "wlanSSID", "string"),
            (148, "flowId", "unsigned"),
            (149, "observationDomainId", "unsigned"),
            (150, "flowStartSeconds", "dateTimeSeconds"),
            (151, "flowEndSeconds", "dateTimeSeconds"),
            (152, "flowStartMilliseconds", "dateTimeMilliseconds"),
            (153, "flowEndMilliseconds", "dateTimeMilliseconds"),
            (154, "flowStartMicroseconds", "dateTimeMicroseconds"),
            (155, "flowEndMicroseconds", "dateTimeMicroseconds"),
            (156, "flowStartNanoseconds", "dateTimeNanoseconds"),
            (157, "flowEndNanoseconds", "dateTimeNanoseconds"),
            (158, "flowStartDeltaMicroseconds", "unsigned"),
            (159, "flowEndDeltaMicroseconds", "unsigned"),
            (160, "systemInitTimeMilliseconds", "dateTimeMilliseconds"),
            (161, "flowDurationMilliseconds", "unsigned"),
            (162, "flowDurationMicroseconds", "unsigned"),
            (163, "observedFlowTotalCount", "unsigned"),
            (164, "ignoredPacketTotalCount", "unsigned"),
            (165, "ignoredOctetTotalCount", "unsigned"),
            (166, "notSentFlowTotalCount", "unsigned"),
            (167, "notSentPacketTotalCount", "unsigned"),
            (168, "notSentOctetTotalCount", "unsigned"),
            (169, "destinationIPv6Prefix", "ipv6Address"),
            (170, "sourceIPv6Prefix", "ipv6Address"),
            (171, "postOctetTotalCount", "unsigned"),
            (172, "postPacketTotalCount", "unsigned"),
            (173, "flowKeyIndicator", "unsigned"),
            (174, "postMCastPacketTotalCount", "unsigned"),
            (175, "postMCastOctetTotalCount", "unsigned"),
            (176, "icmpTypeIPv4", "unsigned"),
            (177, "icmpCodeIPv4", "unsigned"),
            (178, "icmpTypeIPv6", "unsigned"),
            (179, "icmpCodeIPv6", "unsigned"),
            (180, "udpSourcePort", "unsigned"),
            (181, "udpDestinationPort", "unsigned"),
            (182, "tcpSourcePort", "unsigned"),
            (183, "tcpDestinationPort", "unsigned"),
            (184, "tcpSequenceNumber", "unsigned"),
            (185, "tcpAcknowledgementNumber", "unsigned"),
            (186, "tcpWindowSize", "unsigned"),
            (187, "tcpUrgentPointer", "unsigned"),
            (188, "tcpHeaderLength", "unsigned"),
            (189, "ipHeaderLength", "unsigned"),
            (190, "totalLengthIPv4", "unsigned"),
            (191, "payloadLengthIPv6", "unsigned"),
            (192, "ipTTL", "unsigned"),
            (193, "nextHeaderIPv6", "unsigned"),
            (194, "mplsPayloadLength", "unsigned"),
            (195, "ipDiffServCodePoint", "unsigned"),
            (196, "ipPrecedence", "unsigned"),
            (197, "fragmentFlags", "unsigned"),
            (198, "octetDeltaSumOfSquares", "unsigned"),
            (199, "octetTotalSumOfSquares", "unsigned"),
            (200, "mplsTopLabelTTL", "unsigned"),
            (201, "mplsLabelStackLength", "unsigned"),
            (202, "mplsLabelStackDepth", "unsigned"),
            (203, "mplsTopLabelExp", "unsigned"),
            (204, "ipPayloadLength", "unsigned"),
            (205, "udpMessageLength", "unsigned"),
            (206, "isMulticast", "unsigned"),
            (207, "ipv4IHL", "unsigned"),
            (208, "ipv4Options", "unsigned"),
            (209, "tcpOptions", "unsigned"),
            (210, "paddingOctets", "octetArray"),
            (211, "collectorIPv4Address", "ipv4Address"),
            (212, "collectorIPv6Address", "ipv6Address"),
            (213, "exportInterface", "unsigned"),
            (214, "exportProtocolVersion", "unsigned"),
            (215, "exportTransportProtocol", "unsigned"),
            (216, "collectorTransportPort", "unsigned"),
            (217, "exporterTransportPort", "unsigned"),
            (218, "tcpSynTotalCount", "unsigned"),
            (219, "tcpFinTotalCount", "unsigned"),
            (220, "tcpRstTotalCount", "unsigned"),
            (221, "tcpPshTotalCount", "unsigned"),
            (222, "tcpAckTotalCount", "unsigned"),
            (223, "tcpUrgTotalCount", "unsigned"),
            (224, "ipTotalLength", "unsigned"),
            (225, "postNATSourceIPv4Address", "ipv4Address"),
            (226, "postNATDestinationIPv4Address", "ipv4Address"),
            (227, "postNAPTSourceTransportPort", "unsigned"),
            (228, "postNAPTDestinationTransportPort", "unsigned"),
            (229, "natOriginatingAddressRealm", "unsigned"),
            (230, "natEvent", "unsigned"),
            (231, "initiatorOctets", "unsigned"),
            (232, "responderOctets", "unsigned"),
            (233, "firewallEvent", "unsigned"),
            (234, "ingressVRFID", "unsigned"),
            (235, "egressVRFID", "unsigned"),
            (236, "VRFname", "string"),
            (237, "postMplsTopLabelExp", "unsigned"),
            (238, "tcpWindowScale", "unsigned"),
            (239, "biflowDirection", "unsigned"),
            (240, "ethernetHeaderLength", "unsigned"),
            (241, "ethernetPayloadLength", "unsigned"),
            (242, "ethernetTotalLength", "unsigned"),
            (243, "dot1qVlanId", "unsigned"),
            (244, "dot1qPriority", "unsigned"),
            (245, "dot1qCustomerVlanId", "unsigned"),
            (246, "dot1qCustomerPriority", "unsigned"),
            (247, "metroEvcId", "string"),
            (248, "metroEvcType", "unsigned"),
            (249, "pseudoWireId", "unsigned"),
            (250, "pseudoWireType", "unsigned"),
            (251, "pseudoWireControlWord", "unsigned"),
            (252, "ingressPhysicalInterface", "unsigned"),
            (253, "egressPhysicalInterface", "unsigned"),
            (254, "postDot1qVlanId", "unsigned"),
            (255, "postDot1qCustomerVlanId", "unsigned"),
            (256, "ethernetType", "unsigned"),
            (257, "postIpPrecedence", "unsigned"),
            (258, "collectionTimeMilliseconds", "dateTimeMilliseconds"),
            (259, "exportSctpStreamId", "unsigned"),
            (260, "maxExportSeconds", "dateTimeSeconds"),
            (261, "maxFlowEndSeconds", "dateTimeSeconds"),
            (262, "messageMD5Checksum", "octetArray"),
            (263, "messageScope", "unsigned"),
            (264, "minExportSeconds", "dateTimeSeconds"),
            (265, "minFlowStartSeconds", "dateTimeSeconds"),
            (266, "opaqueOctets", "octetArray"),
            (267, "sessionScope", "unsigned"),
            (268, "maxFlowEndMicroseconds", "dateTimeMicroseconds"),
            (269, "maxFlowEndMilliseconds", "dateTimeMilliseconds"),
            (270, "maxFlowEndNanoseconds", "dateTimeNanoseconds"),
            (271, "minFlowStartMicroseconds", "dateTimeMicroseconds"),
            (272, "minFlowStartMilliseconds", "dateTimeMilliseconds"),
            (273, "minFlowStartNanoseconds", "dateTimeNanoseconds"),
            (274, "collectorCertificate", "octetArray"),
            (275, "exporterCertificate", "octetArray"),
            (276, "dataRecordsReliability", "boolean"),
            (277, "observationPointType", "unsigned"),
            (278, "newConnectionDeltaCount", "unsigned"),
            (279, "connectionSumDurationSeconds", "unsigned"),
            (280, "connectionTransactionId", "unsigned"),
            (281, "postNATSourceIPv6Address", "ipv6Address"),
            (282, "postNATDestinationIPv6Address", "ipv6Address"),
            (283, "natPoolId", "unsigned"),
            (284, "natPoolName", "string"),
            (285, "anonymizationFlags", "unsigned"),
            (286, "anonymizationTechnique", "unsigned"),
            (287, "informationElementIndex", "unsigned"),
            (288, "p2pTechnology", "string"),
            (289, "tunnelTechnology", "string"),
            (290, "encryptedTechnology", "string"),
            (291, "basicList", "basicList"),
            (292, "subTemplateList", "subTemplateList"),
            (293, "subTemplateMultiList", "subTemplateMultiList"),
            (294, "bgpValidityState", "unsigned"),
            (295, "IPSecSPI", "unsigned"),
            (296, "greKey", "unsigned"),
            (297, "natType", "unsigned"),
            (298, "initiatorPackets", "unsigned"),
            (299, "responderPackets", "unsigned"),
            (300, "observationDomainName", "string"),
            (301, "selectionSequenceId", "unsigned"),
            (302, "selectorId", "unsigned"),
            (303, "informationElementId", "unsigned"),
            (304, "selectorAlgorithm", "unsigned"),
            (305, "samplingPacketInterval", "unsigned"),
            (306, "samplingPacketSpace", "unsigned"),
            (307, "samplingTimeInterval", "unsigned"),
            (308, "samplingTimeSpace", "unsigned"),
            (309, "samplingSize", "unsigned"),
            (310, "samplingPopulation", "unsigned"),
            (311, "samplingProbability", "float"),
            (312, "dataLinkFrameSize", "unsigned"),
            (313, "ipHeaderPacketSection", "octetArray"),
            (314, "ipPayloadPacketSection", "octetArray"),
            (315, "dataLinkFrameSection", "octetArray"),
            (316, "mplsLabelStackSection", "octetArray"),
            (317, "mplsPayloadPacketSection", "octetArray"),
            (318, "selectorIdTotalPktsObserved", "unsigned"),
            (319, "selectorIdTotalPktsSelected", "unsigned"),
            (320, "absoluteError", "float"),
            (321, "relativeError", "float"),
            (322, "observationTimeSeconds", "dateTimeSeconds"),
            (323, "observationTimeMilliseconds", "dateTimeMilliseconds"),
            (324, "observationTimeMicroseconds", "dateTimeMicroseconds"),
            (325, "observationTimeNanoseconds", "dateTimeNanoseconds"),
            (326, "digestHashValue", "unsigned"),
            (327, "hashIPPayloadOffset", "unsigned"),
            (328, "hashIPPayloadSize", "unsigned"),
            (329, "hashOutputRangeMin", "unsigned"),
            (330, "hashOutputRangeMax", "unsigned"),
            (331, "hashSelectedRangeMin", "unsigned"),
            (332, "hashSelectedRangeMax", "unsigned"),
            (333, "hashDigestOutput", "boolean"),
            (334, "hashInitialiserValue", "unsigned"),
            (335, "selectorName", "string"),
            (336, "upperCILimit", "float"),
            (337, "lowerCILimit", "float"),
            (338, "confidenceLevel", "float"),
            (339, "informationElementDataType", "unsigned"),
            (340, "informationElementDescription", "string"),
            (341, "informationElementName", "string"),
            (342, "informationElementRangeBegin", "unsigned"),
            (343, "informationElementRangeEnd", "unsigned"),
            (344, "informationElementSemantics", "unsigned"),
            (345, "informationElementUnits", "unsigned"),
            (346, "privateEnterpriseNumber", "unsigned"),
            (347, "virtualStationInterfaceId", "octetArray"),
            (348, "virtualStationInterfaceName", "string"),
            (349, "virtualStationUUID", "octetArray"),
            (350, "virtualStationName", "string"),
            (351, "layer2SegmentId", "unsigned"),
            (352, "layer2OctetDeltaCount", "unsigned"),
            (353, "layer2OctetTotalCount", "unsigned"),
            (354, "ingressUnicastPacketTotalCount", "unsigned"),
            (355, "ingressMulticastPacketTotalCount", "unsigned"),
            (356, "ingressBroadcastPacketTotalCount", "unsigned"),
            (357, "egressUnicastPacketTotalCount", "unsigned"),
            (358, "egressBroadcastPacketTotalCount", "unsigned"),
            (359, "monitoringIntervalStartMilliSeconds", "dateTimeMilliseconds"),
            (360, "monitoringIntervalEndMilliSeconds", "dateTimeMilliseconds"),
            (361, "portRangeStart", "unsigned"),
            (362, "portRangeEnd", "unsigned"),
            (363, "portRangeStepSize", "unsigned"),
            (364, "portRangeNumPorts", "unsigned"),
            (365, "staMacAddress", "macAddress"),
            (366, "staIPv4Address", "ipv4Address"),
            (367, "wtpMacAddress", "macAddress"),
            (368, "ingressInterfaceType", "unsigned"),
            (369, "egressInterfaceType", "unsigned"),
            (370, "rtpSequenceNumber", "unsigned"),
            (371, "userName", "string"),
            (372, "applicationCategoryName", "string"),
            (373, "applicationSubCategoryName", "string"),
            (374, "applicationGroupName", "string"),
            (375, "originalFlowsPresent", "unsigned"),
            (376, "originalFlowsInitiated", "unsigned"),
            (377, "originalFlowsCompleted", "unsigned"),
            (378, "distinctCountOfSourceIPAddress", "unsigned"),
            (379, "distinctCountOfDestinationIPAddress", "unsigned"),
            (380, "distinctCountOfSourceIPv4Address", "unsigned"),
            (381, "distinctCountOfDestinationIPv4Address", "unsigned"),
            (382, "distinctCountOfSourceIPv6Address", "unsigned"),
            (383, "distinctCountOfDestinationIPv6Address", "unsigned"),
            (384, "valueDistributionMethod", "unsigned"),
            (385, "rfc3550JitterMilliseconds", "unsigned"),
            (386, "rfc3550JitterMicroseconds", "unsigned"),
            (387, "rfc3550JitterNanoseconds", "unsigned"),
            (388, "dot1qDEI", "boolean"),
            (389, "dot1qCustomerDEI", "boolean"),
            (390, "flowSelectorAlgorithm", "unsigned"),
            (391, "flowSelectedOctetDeltaCount", "unsigned"),
            (392, "flowSelectedPacketDeltaCount", "unsigned"),
            (393, "flowSelectedFlowDeltaCount", "unsigned"),
            (394, "selectorIDTotalFlowsObserved", "unsigned"),
            (395, "selectorIDTotalFlowsSelected", "unsigned"),
            (396, "samplingFlowInterval", "unsigned"),
            (397, "samplingFlowSpacing", "unsigned"),
            (398, "flowSamplingTimeInterval", "unsigned"),
            (399, "flowSamplingTimeSpacing", "unsigned"),
            (400, "hashFlowDomain", "unsigned"),
            (401, "transportOctetDeltaCount", "unsigned"),
            (402, "transportPacketDeltaCount", "unsigned"),
            (403, "originalExporterIPv4Address", "ipv4Address"),
            (404, "originalExporterIPv6Address", "ipv6Address"),
            (405, "originalObservationDomainId", "unsigned"),
            (406, "intermediateProcessId", "unsigned"),
            (407, "ignoredDataRecordTotalCount", "unsigned"),
            (408, "dataLinkFrameType", "unsigned"),
            (409, "sectionOffset", "unsigned"),
            (410, "sectionExportedOctets", "unsigned"),
            (411, "dot1qServiceInstanceTag", "octetArray"),
            (412, "dot1qServiceInstanceId", "unsigned"),
            (413, "dot1qServiceInstancePriority", "unsigned"),
            (414, "dot1qCustomerSourceMacAddress", "macAddress"),
            (415, "dot1qCustomerDestinationMacAddress", "macAddress"),
            (417, "postLayer2OctetDeltaCount", "unsigned"),
            (418, "postMCastLayer2OctetDeltaCount", "unsigned"),
            (420, "postLayer2OctetTotalCount", "unsigned"),
            (421, "postMCastLayer2OctetTotalCount", "unsigned"),
            (422, "minimumLayer2TotalLength", "unsigned"),
            (423, "maximumLayer2TotalLength", "unsigned"),
            (424, "droppedLayer2OctetDeltaCount", "unsigned"),
            (425, "droppedLayer2OctetTotalCount", "unsigned"),
            (426, "ignoredLayer2OctetTotalCount", "unsigned"),
            (427, "notSentLayer2OctetTotalCount", "unsigned"),
            (428, "layer2OctetDeltaSumOfSquares", "unsigned"),
            (429, "layer2OctetTotalSumOfSquares", "unsigned"),
            (430, "layer2FrameDeltaCount", "unsigned"),
            (431, "layer2FrameTotalCount", "unsigned"),
            (432, "pseudoWireDestinationIPv4Address", "ipv4Address"),
            (433, "ignoredLayer2FrameTotalCount", "unsigned"),
            (434, "mibObjectValueInteger", "signed"),
            (435, "mibObjectValueOctetString", "octetArray"),
            (436, "mibObjectValueOID", "octetArray"),
            (437, "mibObjectValueBits", "octetArray"),
            (438, "mibObjectValueIPAddress", "ipv4Address"),
            (439, "mibObjectValueCounter", "unsigned"),
            (440, "mibObjectValueGauge", "unsigned"),
            (441, "mibObjectValueTimeTicks", "unsigned"),
            (442, "mibObjectValueUnsigned", "unsigned"),
            (443, "mibObjectValueTable", "subTemplateList"),
            (444, "mibObjectValueRow", "subTemplateList"),
            (445, "mibObjectIdentifier", "octetArray"),
            (446, "mibSubIdentifier", "unsigned"),
            (447, "mibIndexIndicator", "unsigned"),
            (448, "mibCaptureTimeSemantics", "unsigned"),
            (449, "mibContextEngineID", "octetArray"),
            (450, "mibContextName", "string"),
            (451, "mibObjectName", "string"),
            (452, "mibObjectDescription", "string"),
            (453, "mibObjectSyntax", "string"),
            (454, "mibModuleName", "string"),
            (455, "mobileIMSI", "string"),
            (456, "mobileMSISDN", "string"),
            (457, "httpStatusCode", "unsigned"),
            (458, "sourceTransportPortsLimit", "unsigned"),
            (459, "httpRequestMethod", "string"),
            (460, "httpRequestHost", "string"),
            (461, "httpRequestTarget", "string"),
            (462, "httpMessageVersion", "string"),
            (463, "natInstanceID", "unsigned"),
            (464, "internalAddressRealm", "octetArray"),
            (465, "externalAddressRealm", "octetArray"),
            (466, "natQuotaExceededEvent", "unsigned"),
            (467, "natThresholdEvent", "unsigned"),
            (468, "httpUserAgent", "string"),
            (469, "httpContentType", "string"),
            (470, "httpReasonPhrase", "string"),
            (471, "maxSessionEntries", "unsigned"),
            (472, "maxBIBEntries", "unsigned"),
            (473, "maxEntriesPerUser", "unsigned"),
            (474, "maxSubscribers", "unsigned"),
            (475, "maxFragmentsPendingReassembly", "unsigned"),
            (476, "addressPoolHighThreshold", "unsigned"),
            (477, "addressPoolLowThreshold", "unsigned"),
            (478, "addressPortMappingHighThreshold", "unsigned"),
            (479, "addressPortMappingLowThreshold", "unsigned"),
            (480, "addressPortMappingPerUserHighThreshold", "unsigned"),
            (481, "globalAddressMappingHighThreshold", "unsigned"),
            (482, "vpnIdentifier", "octetArray"),
            (483, "bgpCommunity", "unsigned"),
            (484, "bgpSourceCommunityList", "basicList"),
            (485, "bgpDestinationCommunityList", "basicList"),
            (486, "bgpExtendedCommunity", "octetArray"),
            (487, "bgpSourceExtendedCommunityList", "basicList"),
            (488, "bgpDestinationExtendedCommunityList", "basicList"),
            (489, "bgpLargeCommunity", "octetArray"),
            (490, "bgpSourceLargeCommunityList", "basicList"),
            (491, "bgpDestinationLargeCommunityList", "basicList"),
            (492, "srhFlagsIPv6", "unsigned"),
            (493, "srhTagIPv6", "unsigned"),
            (494, "srhSegmentIPv6", "ipv6Address"),
            (495, "srhActiveSegmentIPv6", "ipv6Address"),
            (496, "srhSegmentIPv6BasicList", "basicList"),
            (497, "srhSegmentIPv6ListSection", "octetArray"),
            (498, "srhSegmentsIPv6Left", "unsigned"),
            (499, "srhIPv6Section", "octetArray"),
            (500, "srhIPv6ActiveSegmentType", "unsigned"),
            (501, "srhSegmentIPv6LocatorLength", "unsigned"),
            (502, "srhSegmentIPv6EndpointBehavior", "unsigned"),
            (503, "transportChecksum", "unsigned"),
            (504, "icmpHeaderPacketSection", "octetArray"),
            (505, "gtpuFlags", "unsigned"),
            (506, "gtpuMsgType", "unsigned"),
            (507, "gtpuTEid", "unsigned"),
            (508, "gtpuSequenceNum", "unsigned"),
            (509, "gtpuQFI", "unsigned"),
            (510, "gtpuPduType", "unsigned"),
            (511, "bgpSourceAsPathList", "basicList"),
            (512, "bgpDestinationAsPathList", "basicList"),
            (513, "ipv6ExtensionHeaderType", "unsigned"),
            (514, "ipv6ExtensionHeaderCount", "unsigned"),
            (515, "ipv6ExtensionHeadersFull", "unsigned"),
            (516, "ipv6ExtensionHeaderTypeCountList", "subTemplateList"),
            (517, "ipv6ExtensionHeadersLimit", "boolean"),
            (518, "ipv6ExtensionHeadersChainLength", "unsigned"),
            (519, "ipv6ExtensionHeaderChainLengthList", "subTemplateList"),
            (520, "tcpOptionsFull", "unsigned"),
            (521, "tcpSharedOptionExID16", "unsigned"),
            (522, "tcpSharedOptionExID32", "unsigned"),
            (523, "tcpSharedOptionExID16List", "basicList"),
            (524, "tcpSharedOptionExID32List", "basicList"),
            (525, "udpSafeOptions", "unsigned"),
            (526, "udpUnsafeOptions", "unsigned"),
            (527, "udpExID", "unsigned"),
            (528, "udpSafeExIDList", "basicList"),
            (529, "udpUnsafeExIDList", "basicList"),
        ];

        elements.iter().for_each(|(id, name, data_type)| {
            self.add_element(
                *id,
                None,
                name.to_string(),
                (*data_type).try_into().unwrap(),
            );
        });
    }
}

impl Default for IERegistry {
    fn default() -> Self {
        Self::new_with_iana_elements()
    }
}
