{
 "title": "RustFlow",
 "tags": [ "rustflow" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "filter" },
   {
    "name": "interval",
    "query": "10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Bits per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_received_ns) AS time,\n       sum(bytes) * 8 / $__interval_s AS bps\nFROM rustflow.flows\nWHERE $__timeFilter(time_received_ns)\nGROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Packets per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(time_received_ns) AS time,\n       sum(packets) / $__interval_s AS pps\nFROM rustflow.flows\nWHERE $__timeFilter(time_received_ns)\nGROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Flows",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT flow_type, sampling_rate, sampler_address, src_addr, dst_addr, proto, tcp_flags, src_port, dst_port, bytes, packets FROM \"rustflow\".\"flows\" ORDER BY time_received_ns DESC LIMIT 1000"
    }
   ]
  }
 ]
}