CREATE DATABASE IF NOT EXISTS rustflow;

CREATE OR REPLACE VIEW rustflow.flows AS
SELECT *
FROM file(
  'flows/**/*.parquet',
  Parquet,
  'flow_type String,
   time_received_ns Nullable(DateTime64(9, ''UTC'')),
   sequence_num UInt32,
   sampling_rate Nullable(UInt32),
   sampler_address Nullable(String),
   time_flow_start_ns Nullable(DateTime64(9, ''UTC'')),
   time_flow_end_ns Nullable(DateTime64(9, ''UTC'')),
   bytes UInt64,
   packets UInt64,
   src_addr Nullable(String),
   dst_addr Nullable(String),
   src_mac Nullable(String),
   dst_mac Nullable(String),
   etype Nullable(UInt16),
   proto Nullable(UInt8),
   src_port Nullable(UInt16),
   dst_port Nullable(UInt16),
   in_if Nullable(UInt32),
   out_if Nullable(UInt32),
   ip_tos Nullable(UInt8),
   ip_ttl Nullable(UInt8),
   tcp_flags Nullable(UInt8),
   icmp_type Nullable(UInt8),
   icmp_code Nullable(UInt8),
   ipv6_flow_label Nullable(UInt32),
   fragment_id Nullable(UInt32),
   fragment_offset Nullable(UInt16),
   src_as Nullable(UInt32),
   dst_as Nullable(UInt32),
   next_hop Nullable(String),
   src_net Nullable(UInt8),
   dst_net Nullable(UInt8),
   bgp_next_hop Nullable(String),
   src_vlan Nullable(UInt16),
   dst_vlan Nullable(UInt16),
   observation_domain_id Nullable(UInt32),
   template_id Nullable(UInt16)'
);
